### ISSUE TITLE
Add the ability to automatically launch the app when the user logs in to the computer

### ISSUE THREAD

**Issue by alobaili** [cs4alhaider/QRCodeHere#2]
It would be awesome if the app can launch automatically when the user logs in to the computer.

Additionally, adding a preference so the user can choose to enable/disable this feature would be great.

**Comment by alobaili** [comment]
Great article I found to help with this: https://jogendra.dev/implementing-launch-at-login-feature-in-macos-apps

I'm currently reading about it.

**Comment by cs4alhaider** [comment]
@alobaili  I use [MeetingBar](https://github.com/leits/MeetingBar) everyday at work and I believe we can get cool stuff from it

**Comment by alobaili** [comment]
I tried following the instructions in the article but for some reason it's not working. I tried creating the AutoLauncher target but I don't have a team so maybe it's a problem with code signing when creating the archive. No matter what I do the app won't launch on login.

This package may also be helpful and provide a ready made solution we can use directly: https://github.com/sindresorhus/LaunchAtLogin

**Comment by cs4alhaider** [comment]
@alobaili I believe we can go ahead with ready made solution as the developer is well known also

**Comment by cs4alhaider** [comment]
@alobaili how is things going with you? do u need any help?

**Comment by alobaili** [comment]
I scrapped the first attempt (implement it myself) and didn't have the time to try the LaunchAtLogin package.

I've turned my attention to the issue of fixing dragging an image with watermark included. I'm almost done with it. I'll probably finish tomorrow or the day after.

Feel free to take this one if you have the time.

**Comment by cs4alhaider** [comment]
@alobaili  ok, I will pick this task

**Comment by cs4alhaider** [comment]
I'm done with this task, also tested it and it's working as expected 👍

Thanks for sharing the above package!

Also, I created a signed version so you can install it and try it out! [QRCodeHere](https://we.tl/t-FH4vsMPIKF)
